@startuml
'https://plantuml.com/class-diagram

+class FrontPage {
    +main(args : String[])
    +start(primaryStage : Stage)

}

+class FrontPageController {

    writer : PrintWriter
    dir : FileChooser
    fileName : String
    stage : Stage
    userFile : File
    openFile : File
    loadFile : File
    input : Scanner
    extension : String
    forward : String
    doc : Document
    +names : List<String>
    +serials : List<String>
    +values : List<Double>
    +namesSorted : List<String>
    +serialsSorted : List<String>
    +valuesSorted : List<Double>
    +OptionsMenu : SplitMenuButton
    +ItemsFound : SplitMenuButton
    +OpenFilePressed()
    +PopulateSearch()
    +Searched()
    +ListViewName : ListView<String>
    +ListViewValue : ListView<Double>
    +ListViewSerial : ListView<String>
    +AllItems : SplitMenuButton
    +SearchBar : TextField
    +ExitPressed()
    +DisplayPressed()
    +HelpPressed()
    +AddItemPressed()
    +ShowListItems()
    +EditItemPressed()
    +SortValuePressed()
    +SortNamePressed()
    +SortSerialPressed()
    +SavePressed()
    +LoadPressed()
}

+class MultipleScenes {
     +MultipleScenes(name : ViewScenes)
}

+enum ViewScenes{
    FrontPage
    AddItem
    +file : String
    +getFile() : String
}

+class ChangeScenes {
    +scene : Scene
    +root : Parent
    +stageScene(scene : Scene)
    +Change(view : ViewScenes)
}

+class AddItemController {

    +DoneButton : Button
    +ItemName : TextField
    +ItemValue : TextField
    +ItemSerial : TextField
    +ShowItemStatus : TextArea
    +checkValue : Double
    +valueCheck : Boolean
    +nameCheck : Boolean
    +serialCheck : Boolean
    +serial : char[]
    +AddPressed()
    +ItemNameEntered()
    +ItemValueEntered()
    +ItemSerialEntered()
    +DonePressed()
    +nameEntry : boolean;
    +valueEntry : boolean
    +serialEntry : boolean
}

+class EditItemController {

    +DoneButton : Button
    +EditName : TextField
    +EditValue : TextField
    +EditSerial : TextField
    +ShowItemStatus : TextArea
    +AllItems : SplitMenuButton
    +counter : int
    +sort : int
    +temp : String
    +serialCheck : boolean
    +nameCheck : boolean
    +valueCheck : boolean
    +serialEdit : boolean
    +nameEdit : boolean
    +valueEdit : boolean
    +serialEntry : boolean
    +nameEntry : boolean
    +valueEntry : boolean
    +checkValue : double
    +serial : char[]
    +ItemNameEntered
    +ItemSerialEntered
    +ItemValueEntered
    +DonePressed
    +EditPressed
    +ViewAllItems
    +SetItems
}
javafx.Application <|-- FrontPage
FrontPageController o--> FrontPage
EditItemController o--> FrontPageController
AddItemController o--> FrontPageController
FrontPage <|-- MultipleScenes
ChangeScenes o--> FrontPageController
FrontPage <|-- ViewScenes



@enduml